# This is a comment.
# Official docs:
#  - https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#  - https://docs.github.com/en/sponsors/getting-started-with-github-sponsors/about-github-sponsors

github: [libranet]
