# This is the local configuration for the poetry-command.
# Poetry provides the ability to have settings that are specific to a project
# by passing the --local option to the config command.
# Please see https://python-poetry.org/docs/configuration/
# > poetry config virtualenvs.create true --local
# > poetry config virtualenvs.in-project true --local

[virtualenvs]

# Create a new virtual environment if one doesn’t already exist. Defaults to true.
create = true

# Create the virtualenv inside the project’s root directory. Defaults to None.
# If set to true, the virtualenv wil be created and expected in a folder named .venv within the root directory of the project.
# If not set explicitly (default), poetry will use the virtualenv from the .venv directory when one is available.
# If set to false, poetry will ignore any existing .venv directory
in-project = true
